"-- Supabase schema for Clinix AI billing flows\n"
"-- Run this in Supabase SQL editor or psql after setting the project DB.\n"
"\n"
"-- Extensions\n"
"create extension if not exists \"pgcrypto\";\n"
"\n"
"-- Claims table: add columns for normalized fields\n"
"alter table public.claims\n"
"  add column if not exists patient_name text,\n"
"  add column if not exists payer_name text,\n"
"  add column if not exists date_of_service date,\n"
"  add column if not exists total_charge numeric,\n"
"  add column if not exists service_line_count integer,\n"
"  add column if not exists primary_diagnosis_code text,\n"
"  add column if not exists updated_at timestamptz default now();\n"
"\n"
"create index if not exists claims_user_id_idx on public.claims (user_id);\n"
"create index if not exists claims_status_idx on public.claims (status);\n"
"create index if not exists claims_date_of_service_idx on public.claims (date_of_service desc nulls last);\n"
"\n"
"-- Diagnoses per claim\n"
"create table if not exists public.claim_diagnoses (\n"
"  id uuid primary key default gen_random_uuid(),\n"
"  claim_id uuid references public.claims(id) on delete cascade,\n"
"  code text not null,\n"
"  description text,\n"
"  priority int,\n"
"  created_at timestamptz default now()\n"
");\n"
"create index if not exists claim_diagnoses_claim_id_idx on public.claim_diagnoses (claim_id);\n"
"\n"
"-- Service lines per claim\n"
"create table if not exists public.claim_service_lines (\n"
"  id uuid primary key default gen_random_uuid(),\n"
"  claim_id uuid references public.claims(id) on delete cascade,\n"
"  code text not null,\n"
"  description text,\n"
"  modifiers text[] default '{}',\n"
"  diagnosis_pointers int[] default '{}',\n"
"  service_date_from date,\n"
"  service_date_to date,\n"
"  units numeric,\n"
"  charge numeric,\n"
"  created_at timestamptz default now()\n"
");\n"
"create index if not exists claim_service_lines_claim_id_idx on public.claim_service_lines (claim_id);\n"
\n"
"-- Simple status enum (optional). Uncomment to enforce typed statuses.\n"
"-- create type public.claim_status as enum ('draft','submitted','accepted','denied','rejected','paid');\n"
"-- alter table public.claims alter column status type public.claim_status using status::public.claim_status;\n"

